services:

  nginx:
    image: nginx
    container_name: nginx
    shm_size: '300m'
    depends_on:
      - traefik
    ports:
     - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    restart: unless-stopped

  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 8080:8080
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped