services:

  nginx:
    image: nginx
    container_name: proxy
    depends_on:
      - traefik
    ports:
     - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro

  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 8080:8080
    command:
      # - --logLevel=DEBUG
      - --api.insecure=true
      # Enabling docker provider
      - --providers.docker=true
      # Do not expose containers unless explicitly told so
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped